
name: Gradle Package

on:
  release:
    types: [created]

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
    - name: Test
      run: |
        ./gradlew test
    - name: Get tag
      id: tag
      uses: dawidd6/action-get-tag@v1
      with:
        strip_v: false
    - name: Publish
      run: |
        ./gradlew publish
      env:
        PUBLISH_GITHUB_USERNAME: ${{ secrets.PUBLISH_GITHUB_USERNAME }}
        PUBLISH_GITHUB_PASSWORD: ${{ secrets.PUBLISH_GITHUB_PASSWORD }}
        PUBLISH_PACKAGE_VERSION: ${{ steps.tag.outputs.tag }}
