# This is a basic workflow to help you get started with Actions

name: publish

on:
  release:
    types: [created]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Test
        run: gradle test
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Get tag
        id: tag
        uses: dawidd6/action-get-tag@v1
        with:
          strip_v: false
      - name: Publish
        run: gradle publish
    env: 
      GITHUB_USERNAME: ${{ secrets.GITHUB_USERNAME }}
      GITHUB_PASSWORD: ${{ secrets.GITHUB_PASSWORD }}
      PACKAGE_VERSION: ${{ steps.tag.outputs.tag }}
